### ISSUE TITLE
[NEW FEATURE]  Bootloader erases too much Flash?

### ISSUE THREAD

**Issue by fleborne** [Luos-io/luos_engine#150] opened 2022-02-04 10:55 UTC
**What feature would you like to be included in Luos?**

This issue could be related to Luos-io/luos_engine#202

Just before flashing a new firmware through the bootloader, the Flash is erased. In the current implementation, the whole Flash after `APP_ADDRESS` is erased, whereas only the pages needed to fit the new firmware could be erased.

Because of this behaviour, the user can't use the Flash pages located after their app to store values. Only the shared memory seems to remain unerased.

**Comment by ncros3** [comment] 2022-02-04 14:14
Hello @fleborne , you're right and I will fix this. I think we can close this issue and only keep [issue 40](https://github.com/Luos-io/LuosHAL/issues/40) because the problem is located in the luos HAL.

**Comment by JeromeGalan** [comment] 2022-06-29 12:10
Done in luos engine 2.5.0

**Closed by JeromeGalan** 2022-06-29 12:10 UTC
